import { ensureDir } from "@std/fs";
import { join, relative } from "@std/path";
import { parseRunesProps } from "./scanner.ts";

export interface EmitOptions {
	componentPath: string;
	componentName: string;
	outputDir: string;
	target: "react" | "vue";
	bindableProps?: string[];
}

/**
 * Emits a typed .tsx or .ts adapter file for a given Svelte component.
 */
export async function emitWrapper({
	componentPath,
	componentName,
	outputDir,
	target,
	bindableProps,
}: EmitOptions): Promise<string> {
	await ensureDir(outputDir);
	const relativeImport = relative(outputDir, componentPath).replace(/\\/g, "/");

	let resolvedBindables = bindableProps;
	if (!resolvedBindables) {
		try {
			const content = await Deno.readTextFile(componentPath);
			resolvedBindables = parseRunesProps(content).bindableProps;
		} catch {
			resolvedBindables = [];
		}
	}

	if (target === "react") {
		const filePath = join(outputDir, `${componentName}.tsx`);
		const bindingCallbacks = (resolvedBindables ?? [])
			.map((p) => {
				const capitalized = p.charAt(0).toUpperCase() + p.slice(1);
				return `  on${capitalized}Change?: (value: any) => void;\n`;
			})
			.join("");

		const code = `// Generated by @arkano/cli. Do not edit directly.
import React from 'react';
import { arkano } from '@arkano/react';
import Svelte${componentName} from '${relativeImport}';
import type { ComponentProps } from 'svelte';

export const ${componentName} = arkano(Svelte${componentName});
export type ${componentName}Props = ComponentProps<typeof Svelte${componentName}> & {
  as?: 'span' | 'div' | 'section';
  className?: string;
  ref?: React.Ref<HTMLElement>;
${bindingCallbacks}};
export default ${componentName};
`;
		await Deno.writeTextFile(filePath, code);
		return filePath;
	}

	if (target === "vue") {
		const filePath = join(outputDir, `${componentName}.ts`);
		const bindingEvents = (resolvedBindables ?? [])
			.map((p) => {
				return `  'onUpdate:${p}'?: (value: any) => void;\n`;
			})
			.join("");

		const code = `// Generated by @arkano/cli. Do not edit directly.
import { arkano } from '@arkano/vue';
import Svelte${componentName} from '${relativeImport}';
import type { ComponentProps } from 'svelte';

export const ${componentName} = arkano(Svelte${componentName});
export type ${componentName}Props = ComponentProps<typeof Svelte${componentName}> & {
  as?: 'span' | 'div' | 'section';
${bindingEvents}};
export default ${componentName};
`;
		await Deno.writeTextFile(filePath, code);
		return filePath;
	}

	throw new Error(`Unsupported target framework: ${target}`);
}
