import { ensureDir } from "jsr:@std/fs/ensure-dir";
import { join, relative } from "node:path";

export interface EmitOptions {
	componentPath: string;
	componentName: string;
	outputDir: string;
	target: "react" | "vue";
}

/**
 * Emits a typed .tsx or .ts adapter file for a given Svelte component.
 */
export async function emitWrapper({
	componentPath,
	componentName,
	outputDir,
	target,
}: EmitOptions): Promise<string> {
	await ensureDir(outputDir);
	const relativeImport = relative(outputDir, componentPath).replace(/\\/g, "/");

	if (target === "react") {
		const filePath = join(outputDir, `${componentName}.tsx`);
		const code = `// Generated by @arkane/cli. Do not edit directly.
import React from 'react';
import { arkane } from '@arkane/react';
import Svelte${componentName} from '${relativeImport}';
import type { ComponentProps } from 'svelte';

export const ${componentName} = arkane(Svelte${componentName});
export type ${componentName}Props = ComponentProps<typeof Svelte${componentName}> & {
  as?: 'span' | 'div' | 'section';
  className?: string;
  ref?: React.Ref<HTMLElement>;
};
export default ${componentName};
`;
		await Deno.writeTextFile(filePath, code);
		return filePath;
	}

	if (target === "vue") {
		const filePath = join(outputDir, `${componentName}.ts`);
		const code = `// Generated by @arkane/cli. Do not edit directly.
import { arkane } from '@arkane/vue';
import Svelte${componentName} from '${relativeImport}';

export const ${componentName} = arkane(Svelte${componentName});
export default ${componentName};
`;
		await Deno.writeTextFile(filePath, code);
		return filePath;
	}

	throw new Error(`Unsupported target framework: ${target}`);
}
